### ISSUE TITLE
20 song per album Limit?

### ISSUE THREAD

**Issue by eoppe1022** [charlie86/spotifyr#11]
Seems like there's a 20 song limit per album. 

For example, this album should have 43 tracks, but only gets data for 20:

`get_artist_audio_features("Minutemen") %>% filter(album_name == "Double Nickels On The Dime")`

Any idea if that's on my end and/or if there's a way to fix that?

**Comment by charlie86** [comment]
@eoppe1022 thanks for pointing this out! That endpoint has a default limit to 20. I just pushed a fix that increases batches the tracks in groups of 50, so there should be no limit anymore.
