### ISSUE TITLE
 genius reverse dependency to CRAN 

### ISSUE THREAD

**Issue by JosiahParry** [charlie86/spotifyr#112]
If I don't commit or comment by Sunday morning please annoy me about it.

**Comment by JosiahParry** [comment]
Submitted to CRAN. Forgot title case....of course. Should be accepted soon.

**Comment by pricejt75** [comment]
This may be a dumb question, but what is a reverse dependency and will this correct the error: 
"Error: Failed to install 'spotifyr' from GitHub:
  (converted from warning) package ‘genius’ is not available (for R version 4.0.0)"?

**Comment by JosiahParry** [comment]
this is my fault. Working to fix that right now. genius is currently in the CRAN gods' hands right now. In essence some of the functions inside of spotifyr require functions from genius. You can install genius with `remotes::install_github("josiahparry/genius")`. Then `remotes::install_github("charlie86/spotifyr")`

**Comment by rafabelokurows** [comment]
I was to able to install "genius" then "spotifyr" through these commands a few days back, just had to manually update the version of some other libraries which were not up to date.
When I tried installing genius, I kept getting the message: "package xxx is in version 0.1 it should be on 0.2", stuff like that. So I updated each one manually, installed genius and then installed spotifyr.
But I don't mean to complain, or anything, I'm just saying that there was/is a workaround :)
BTW, thanks for all your effort on this, Josiah and Charlie! I really appreciate the libraries and all the work you guys have put into them!

**Comment by JosiahParry** [comment]
Thanks @rafabelokurows! I'm so sorry for the headache!

**Comment by JosiahParry** [comment]
Update: `genius` has a dependency on `tidyr` which has a dep on `ellipsis`. `ellipsis` suddenly is failing builds on CRAN checks (see https://github.com/r-lib/ellipsis/issues/33). Which means this may be delayed until above is addressed

**Comment by rafabelokurows** [comment]
that was no problem at all, @JosiahParry... I managed to install it just fine and now I'm playing around with some visualizations based on Foo Fighters songs 🎧🎸🤘🏻 hope the issue is resolved soon! :)

**Comment by JosiahParry** [comment]
reverse dependency build error from https://github.com/r-lib/ellipsis/issues/33 has been solved. Resubmitting genius to CRAN.

**Comment by chris-billingham** [comment]
@JosiahParry How did the submission go?

**Comment by JosiahParry** [comment]
@chris-billingham currently pending manual inspection! 🤞

**Comment by JosiahParry** [comment]
On it's way to CRAN!

**Comment by JosiahParry** [comment]
we're up and running https://cran.r-project.org/
