### ISSUE TITLE
package ‘spotifyr’ is not available (for R version 3.6.1)

### ISSUE THREAD

**Issue by anjumfarook** [charlie86/spotifyr#123]
Do I need an earlier version of R to use spotifyr?

**Comment by niessen** [comment]
Unfortunately, the package ist still archived on CRAN (#119)
You can install from GitHub with 
`devtools::install_github('charlie86/spotifyr')`

**Comment by antaldaniel** [comment]
The development version of the package shoud run with R (>= 3.3.0).  A new CRAN release is coming.
