### ISSUE TITLE
Issue with "return_closest_artist" returning most popular similar artist, not exact match

### ISSUE THREAD

**Issue by eoppe1022** [charlie86/spotifyr#13]
Apologies for raising all of these issues at once.

When i look up the band "Earth", the data returned is of "Earth, Wind & Fire". For some reason, this seems to be a new problem, because it's definitely worked in the past. 

I realized that when I search "Earth" in Spotify, the top result is "Earth, Wind & Fire", so I'm wondering if this is more of a Spotify issue than with the function. Maybe there's a way to search for artists so `if exact match, return exact match -- otherwise, return_closest_artist`.

**Comment by charlie86** [comment]
No worries, I really appreciate you bringing these up! Totally agree with this and just incorporated it
