### ISSUE TITLE
Not all of artist's albums show data (though album is on Spotify)

### ISSUE THREAD

**Issue by eoppe1022** [charlie86/spotifyr#15]
One thing I've noticed is that, when I want to find data for Run the Jewels' self-titled album, "Run the Jewels", all that shows up is their instrumental album, even though their regular self-titled album is on Spotify. Any idea what's going on here?

EX: 

`get_artist_albums("run the jewels")`

**Comment by charlie86** [comment]
@eoppe1022 Thanks for pointing this out.

I tried to filter out remastered/deluxe/anniversary editions, and it looks like I went to far. I think the best option is to have this "album consolidation" be an optional argument so you can toggle this on/off. I'll try to get to it this weekend.

**Comment by eoppe1022** [comment]
Awesome. Yeah that's a great idea..

**Comment by eoppe1022** [comment]
I've been thinking about this a bit, and maybe you could do something along the lines of when searching for an album:

1. See which results return the closest album matches
2. filter out ones that contain "Deluxe, Special, Bonus, Anniversary, Version, Edition"
3. If there are any results left, pick that -- if not, pick one with one of the above terms

**Comment by charlie86** [comment]
@eoppe1022 great suggestion! just updated and pushed to master
