### ISSUE TITLE
problem with "get_my_saved_tracks()"- ' type parameter'

### ISSUE THREAD

**Issue by Toozig** [charlie86/spotifyr#154]
first of all, Thank you for this! 
you did really hard work which makes life easier :)

I'm trying to get ALL of my saved tracks.

when I try to use the standard function, I get this message:
_> r <-get_my_saved_tracks()
Error: The type parameter must be either 'artists' or 'tracks'._
there is no possibility to add 'type' parameter to the function. 

and when I try to use get_my_top_artists_or_tracks(type='artist', offset=x)
I get empty list when x>= 50. I have more than 100 saved tracks.

Again, your library is great :) 
Thanks!

**Comment by antaldaniel** [comment]
This is identical to an earlier bug that is already fixed. Did you try version 2.2.2?

**Comment by Toozig** [comment]
Thank you so much for the VERY fast replay.
Indeed it worked when I updated to 2.2.2
