### ISSUE TITLE
get_my_saved_tracks() returning wrong error message

### ISSUE THREAD

**Issue by corridordigital** [charlie86/spotifyr#157]
Hi, 
I'm trying to get my saved tracks metadata : 

`get_my_saved_tracks(include_meta_info = TRUE)`

But I keep getting this error : `Error : The type parameter must be either 'artists' or 'tracks'.`
There is no `type` parameter for this function, and I tried setting it in `alidate_parameters(artists_or_tracks = 'tracks')`

Any idea what this could be ? 
Thanks a lot.

**Comment by condwanaland** [comment]
+1, also getting this error in the same circumstances

**Comment by antaldaniel** [comment]
This is a duplicate of [154](https://github.com/charlie86/spotifyr/issues/154)
