### ISSUE TITLE
The scopes() function points to a defunct URL, causing downstream issues. 

### ISSUE THREAD

**Issue by dwh1142** [charlie86/spotifyr#160]
The `spotifyr::scopes()` function, which `spotifyr::get_spotify_authorization_code()`, relies on, points to this page: https://developer.spotify.com/documentation/general/guides/scopes/. This url comes back with a 404 Error, and looks like it no longer exists.

I believe it should be pointing here instead: https://developer.spotify.com/documentation/general/guides/authorization/scopes/

Because many other functions are calling `spotifyr::get_spotify_authorization_code()` for authorization, this is causing all kinds of downstream issues. 

See this StackOverflow question: 
https://stackoverflow.com/questions/69649706/error-while-trying-to-extract-spotify-data-using-r

**Comment by apsteinmetz** [comment]
It's a simple matter of changing to the correct url in utils.r::scopes().  When I do that CMD check passes that function.  I am not fluent in github pull requests or I would be happy to do it.

However there is another check failure involving a bad URL.  I don't know if they are related:
  [1] 3
  > get_category_playlists('party', country = 'BR')
  Error in as.character(url) : 
    cannot coerce type 'closure' to vector of type 'character'
  Calls: get_category_playlists ... handle_name -> build_url -> stopifnot -> is.url -> parse_url
  Execution halted

**Comment by antaldaniel** [comment]
Same as [#160](https://github.com/charlie86/spotifyr/issues/160) .
