### ISSUE TITLE
bad variable in browse::get_category_playlists()

### ISSUE THREAD

**Issue by apsteinmetz** [charlie86/spotifyr#161]
Check reveals this:
  [1] 3
  > get_category_playlists('party', country = 'BR')
  Error in as.character(url) : 
    cannot coerce type 'closure' to vector of type 'character'
  Calls: get_category_playlists ... handle_name -> build_url -> stopifnot -> is.url -> parse_url
  Execution halted

This line:
 `   res <- RETRY('GET', url, query = params, encode = 'json', terminate_on = c(401, 403, 404))`
does not reference "url" as a string variable, but the function "url()"

I think "query_url" what is meant
`   res <- RETRY('GET', query_url, query = params, encode = 'json', terminate_on = c(401, 403, 404))`

The function passes check this way.

_Originally posted by @apsteinmetz in https://github.com/charlie86/spotifyr/issues/160#issuecomment-955323286_

**Comment by antaldaniel** [comment]
@apsteinmetz  Thank you very much, very sharp eyes!  I went back to this issue many times, and did not spot the obvious error that you did. Included in 2.2.3.
