### ISSUE TITLE
Error in get_my_top_artists_or_tracks

### ISSUE THREAD

**Issue by sydneyfiller-ua** [charlie86/spotifyr#163]
I get the following error when I run code, I've tried many different parameter values and configurations. The same code works fine for other functions (get_artist_audio_features)

Error in token$sign(req$method, req$url): attempt to apply non-function
Request failed [ERROR]. Retrying in 1 seconds...
Error in token$sign(req$method, req$url): attempt to apply non-function
Request failed [ERROR]. Retrying in 3.5 seconds...
Error in token$sign(req$method, req$url) : attempt to apply non-function

`library(ggplot2)
library(data.table)
library(dplyr)
library(ggridges)
library(spotifyr)
library(ggpmisc)
library(gridExtra)

Sys.setenv(SPOTIFY_CLIENT_ID = '-')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '-)
access_token <- get_spotify_access_token()
#radiohead <- get_artist_audio_features('radiohead')

top_trax <- get_my_top_artists_or_tracks(type='artists', limit=20, offset=0, time_range='long_term') %>%
  select(name, artist.name, album.name)
  kable()
# `

**Comment by antaldaniel** [comment]
Same as [#160](https://github.com/charlie86/spotifyr/issues/160)
