### ISSUE TITLE
Authorization error: could not find function "get_spotify_authorization_code"

### ISSUE THREAD

**Issue by Rafiahmed16** [charlie86/spotifyr#169]
I tried running multiple versions of getting the access token but they all give the same error: could not find function "get_spotify_authorization_code". 

For instance, I tried id <- ‘your client ID’
secret <- ‘your client secret’
Sys.setenv(SPOTIFY_CLIENT_ID = id)
Sys.setenv(SPOTIFY_CLIENT_SECRET = secret)
access_token <- get_spotify_access_token().  OR 

Sys.setenv(SPOTIFY_CLIENT_ID = 'my id')
Sys.setenv(SPOTIFY_CLIENT_SECRET = 'my secret')
spotifyr::get_spotify_authorization_code(client_id = Sys.getenv("SPOTIFY_CLIENT_ID"),
client_secret = Sys.getenv("SPOTIFY_CLIENT_SECRET"),
scope = spotifyr::scopes)

as well as the get_spotify_access_token() / get_spotify_authorization_code() code specifically from the spotifyr package pdf file of different codes. I downloaded the Spotifyr package successfully and inputed my client ID and client secret accurately but I'm not sure why I am getting this error for all the codes displayed above. Is anyone else facing the same issue? How I solve this authorization issue? 

Additionally, I tried to run other codes e.g. get my playlists from my spotify account and I get <could not find function "get_user_playlists"> Is this because my access token code is not working?

**Comment by mfermillan** [comment]
add the library at the beginning of the script 

```
install.packages('spotifyr')
library(spotifyr)

Sys.setenv(SPOTIFY_CLIENT_ID = '83c1f5403e0041af94284639b5ef0aa2')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '89f47a4d82c349819ba0139f91f7a5e4')

access_token <- get_spotify_access_token()
```
