### ISSUE TITLE
Problems about credentials

### ISSUE THREAD

**Issue by dadosdelaplace** [charlie86/spotifyr#176]
Hi!

After registering my Spotify's App, and fixing Sys.getenv("SPOTIFY_CLIENT_ID") and Sys.getenv("SPOTIFY_CLIENT_SECRET") (with the keys provided by Spotify) I get the following error

Error in get_spotify_access_token
Could not authenticate with given Spotify credentials:
Invalid client

**Comment by VerbingNouns** [comment]
I'm also having credentials problems today.

`get_spotify_authorization_code()` returns:
`<simpleError in open.connection(x, "rb"): SSL certificate problem: certificate has expired>`

**Comment by antaldaniel** [comment]
I think that something was not correctly copied to your workspace.
