### ISSUE TITLE
get_genre_artists() is broken when searching two-words genres 

### ISSUE THREAD

**Issue by dejan94it** [charlie86/spotifyr#187]
Example:
get_genre_artists('contemporary classical', limit = 50, offset = 0) 

It gives empty result because it parses whitespaces in URL wrong. 
it needs %20 as whitespace in query

**Comment by antaldaniel** [comment]
@dejan94it  can you please check version 2.2.4.0001 if it is working with you?  The problem was different, but I think that it should be alright now.

**Comment by dejan94it** [comment]
@antaldaniel  It seems working now!
Thanks
