### ISSUE TITLE
Remove `genius` dependency 

### ISSUE THREAD

**Issue by JosiahParry** [charlie86/spotifyr#188]
heya! I'm not longer maintaining the genius library and want to archive it on CRAN. The package hasn't worked appropriately for quite some time.  Can we remove the genius dependency so I can archive the package without taking down spotifyr?

**Comment by charlie86** [comment]
@JosiahParry hey! Hope all is well. No worries - feel free to go ahead and archive, and I'll monitor and update.

**Comment by antaldaniel** [comment]
Hi Josiah, 

I am now maintaining the CRAN process, and there are a few small changes that should go into the next full CRAN release, as there are a few other pull requests that need to be incorporated. 

Unless @charlie86 wants to do it, I gladly remove the genius dependency.  Also, if you want to keep genius as a package on CRAN but lack time to maintain it, I can take over the maintainer role there, too. 

Even in this case, removing the genius as a dependency is safer than writing a vignette on how the two packages can work in harmony. 

Best regards, 
Daniel

**Comment by JosiahParry** [comment]
@antaldaniel PR is made. The only change I think that is worth double checking is `get_album_data()` since this is no longer returning lyrics it may cause backward compatible breaking changes. The rest is unchanged.
