### ISSUE TITLE
Illegal scope error while trying to authenticate app

### ISSUE THREAD

**Issue by starship9** [charlie86/spotifyr#198]
Hello.

I am not certain why, but a project I was working on is currently failing while trying to authorize my access token. I am unsure what changed, since this was working earlier.

I get an "Illegal scope" error as soon as I try to run any functions that require authentication.

The section below does not work:
```
spotify_token <- get_spotify_access_token()
get_my_recently_played(limit = 10) %>%
  names()
```
The API variables are declared in my .Renviron similar to:

```
SPOTIFY_CLIENT_ID = "ID_HERE"
SPOTIFY_CLIENT_SECRET = "SECRET_HERE"

```

**Comment by arisalissandrakis** [comment]
Not entirely sure if it helps but I had a similar issue recently (code working and then suddenly not) and the way I solved it was by restricting some of the scopes (cause by default all scopes are used).  So check the possible scopes in "scopes()" and just use only some of them in the "get_spotify_authorization_code()"; e.g. in my case 

> get_spotify_authorization_code(scope = scopes()[c(7,8,9,10,14,15)])

works, which is a bit of informed trial and error. I have not investigated further to see which scope actually causes the issue.

**Comment by SchillerQuinn** [comment]
Update:

You need to create an authorization object and pass it into your functions or this error will keep on coming up because by default all spotifyr calls use the default `get_spotify_access_token()` call which is broken 

```
auth_object <- get_spotify_authorization_code(scope = scopes()[c(7,8,9,10,14,15)])
get_show("3kDS5MRlBl53tA3MRGqLzx", authorization = auth_object)
```

**Comment by stantis** [comment]
I'm trying get_playlist and get_playlist_audio_features using this approach, and I'm getting the error: `Error in as.vector(x, "character") : 
  cannot coerce type 'environment' to vector of type 'character'`
  
 The auth_object works fine for get_show but not for the above commands. Any ideas?
