### ISSUE TITLE
Change geniusR to geniusr

### ISSUE THREAD

**Issue by ben519** [charlie86/spotifyr#26]
`devtools::install_github('charlie86/spotifyr')` currently gives an error and I believe it's because you have `import(geniusR)` instead of `import(geniusr)` (and I think geniusR shows up in a few other places).

Great package btw!

**Comment by charlie86** [comment]
@ben519 Thanks for pointing this out! The problem is there are multiple Genius R packages. This is the one I'm trying to use: https://github.com/josiahparry/geniusR, but there's one on CRAN that's all lower case. I'll update the docs soon and try to see if we can reconcile the names somehow
