### ISSUE TITLE
Add create_user_playlist() function

### ISSUE THREAD

**Issue by dylanjm** [charlie86/spotifyr#29]
I've been playing around with a fork trying to create a `create_user_playlist()` function that just takes a playlist name and pushes to your profile. I think this can be created through a similar function as the `get_user_playlists()` function. 

I don't know enough about REST frameworks to quite get this to work but I'm thinking something like this could work:

```
RETRY('POST', url = endpoint, query = list(authorization = access_token, name = "Test"), quiet = TRUE,
      encode = "json")
```
Is this possible, would you accept a pull request trying to map this out?

**Comment by charlie86** [comment]
Love this idea! I'd definitely accept a PR

**Comment by Phippsy** [comment]
Hi all - I'd love to help with this. I believe I could get a basic function working but may need some help from charlie86 to have the function follow precedent of existing functions in the package. I'm not familiar with parallel way of working and it looks like this is incorporated. Will have a go if I can and share ideas.

**Comment by Phippsy** [comment]
New pull requested added to create playlists and add tracks to playlists:
#46

**Comment by charlie86** [comment]
Merged
