### ISSUE TITLE
get_artist_features not working

### ISSUE THREAD

**Issue by filipwastberg** [charlie86/spotifyr#3]
I am trying to pull down data from the Swedish band kent via spotfiyr and got into some trouble.

This code is accompanied with the following error:
```kent_df <- get_artist_audio_features("kent")```
```
Error in overscope_eval_next(overscope, expr) : 
  object 'base_album' not found
```
In the `get_artist_audio_features()` `slice`is used to filter? Or am I missing something? So when I use `get_artists("kent")` I return _kent jones_, not the Swedish band _kent_. 

Anyway when changing from slice to filter I managed to download the data, but only if I explicitly type the band name in the actual function, which isn't very good for a general function.

```
get_artist_audio_features_ed <- function (artist_name, access_token = get_spotify_access_token()) 
{
  artist <- get_artists(artist_name) %>% filter(artist_name == "kent") %>% select(artist_uri) %>% 
    .[[1]]
  albums <- get_albums(artist) %>% select(-c(base_album, num_albums, num_base_albums, album_rank))
  album_popularity <- get_album_popularity(albums)
  tracks <- get_album_tracks(albums)
  track_features <- get_track_audio_features(tracks)
  track_popularity <- get_track_popularity(tracks)
  tots <- albums %>% left_join(album_popularity, by = "album_uri") %>% 
    left_join(tracks, by = "album_name") %>% left_join(track_features, 
                                                       by = "track_uri") %>% left_join(track_popularity, by = "track_uri")
  return(tots)
}
```
Changing form slice to `filter(artist_name == artist_name)`does not work. It generates:
```Error: length(url) == 1 is not TRUE```

Seems like a such a simple problem but I can't seem to figure it out. 

Any idea on how to solve it?

**Comment by charlie86** [comment]
Hey Filip,

Thanks for flagging this. The get_artists() function currently grabs the
first artist found via the Search endpoint, which isn't necessarily what
you're looking for. The length(url) == 1 error looks to result from there
being more than one artist matching the exact name "kent". A potential
solution could be showing the users a list of artists and asking them which
one they want to return...any ideas? I'm always open to PRs and will get to
it when I can - the current solution seems to work for the majority of
artists, but I agree it should be updated.

Cheers,
Charlie

**Comment by charlie86** [comment]
Hey Filip - I've just pushed a fix to prompt the user to select and artist, so this issue should be fixed!
