### ISSUE TITLE
bypass manual artist name input for get_artist_audio_features()

### ISSUE THREAD

**Issue by skurp** [charlie86/spotifyr#30]
I've modified this function to bypass the need to type in the artist name when looping through a list of known correct artist names. I think adding an argument of something like: `exact_name = T/F`so users can efficiently loop through would help. Any thoughts about this?

**Comment by charlie86** [comment]
@skurp totally agree! in fact, the development version has already implemented similar behavior. You can install it with `devtools::install_github('charlie86/spotifyr')`

I'm hoping to do another CRAN release at some point, but getting past all the checks is kind of annoying.

**Comment by dannijt** [comment]
Hi @skurp and @charlie86 Can either of you tell me how to do this? I am using the development version.

**Comment by skurp** [comment]
If you are having trouble installing the development version it is because `geniusR` is now a dependency. You need to `devtools::install_github("josiahparry/geniusR")` and then `library(geniusR)` before installing the latest version. Following this, `get_artist_audio_features()` contains a parameter `return_closest_artist = TRUE`. Please see `?get_artist_audio_features()`.
