### ISSUE TITLE
filter album dupes more aggresively

### ISSUE THREAD

**Issue by charlie86** [charlie86/spotifyr#34]

**Comment by charlie86** [comment]
get_artist_albums() tries to filter out duplicate albums by stripping out extra added on text from album names (e.g. "live edition", "remastered"), but some dupes still slip through. Look at Miles Davis for some examples

**Comment by shermstats** [comment]
Example:

Miles Davis scored a French movie called Ascenseur pour l'échafaud.  Spotify has "Ascenseur pour l'échafaud", "Ascenseur pour l'echafaud" (no accent), and "Ascenceur pour l'échafaud" (switches the s for a c).

**Comment by charlie86** [comment]
@shermstats After thinking more about it, I'm going to leave this up to the end user. Since there's no way of knowing what people would like to return, it's safer to return everything spotify has.
