### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by skurp** [charlie86/spotifyr#35]
I am receiving 

    Error in curl::curl_fetch_memory(url, handle = handle) : 
      SSL certificate problem: Invalid certificate chain
 
intermediately when `get_album_data()` and `get_artist_albums()` are called. I do not believe it has to do with my personal SSL handshake, but I think it has to do with too many requests too rapidly to the spotify server (or something?) because sometimes the requests work. I don't know much about this. Surely will help if you have some insight or have noticed this in the currently dev version.

**Comment by charlie86** [comment]
@skurp I think this may actually be due to the parallelization - do you have an example of the code you were running?

**Comment by skurp** [comment]
`get_artist_albums('Wild child')` _usually_ returns the SSL certificate problem (and flounders for a long time doing it). `get_artist_albums('Wild child', parallelize = FALSE)` successfully returns a tibble.

**Comment by charlie86** [comment]
@skurp thanks for pointing this out. I'll try to dig more into that error, and in the meantime will set `parallelize = FALSE` by default.

**Comment by charlie86** [comment]
This seems to have been fixed with https://github.com/charlie86/spotifyr/commit/e97bc1e15edf2dc62ca3a25beeef2cf3aecf8a7b
