### ISSUE TITLE
Look into oauth without browser

### ISSUE THREAD

**Issue by charlie86** [charlie86/spotifyr#38]

**Comment by skurp** [comment]
As in: 

1. login to spotify developers dashboard

2. Register new app on dashboard

3. grab client ID and client secret

4. Save values as env vars

?

**Comment by charlie86** [comment]
@skurp Not exactly, the issue is I'm not able to run any of the functions that use the authorization code flow (e.g. `get_my_recently_played()`) on a headless server.

As an example use case, I'd like to be able to run these on a remote machine on a cron and save the data over time.

**Comment by skurp** [comment]
Are you developing this currently under get_spotify_authorization_code()?

**Comment by skurp** [comment]
Nevermind I see I am working on it!

**Comment by skurp** [comment]
Oauth2.0 requires a browser for user consent **once**. 

The `googlesheets` package [suggests a workflow](https://cran.r-project.org/web/packages/googlesheets/vignettes/managing-auth-tokens.html) where the user authenticates once on a machine with a browser, saves the token as .rds, and moves the token to a remote machine. A stale OAuth token will auto-refresh with this workflow.

I updated `get_spotify_authorization_code()` to work correctly, and I can add a readme how-to if you like this idea.

**Comment by charlie86** [comment]
@skurp That sounds awesome! Would love to incorporate your changes. Do you have a PR?

**Comment by charlie86** [comment]
@wconnell ^
