### ISSUE TITLE
get_playlist_audio_features passes show_progress to functions that do not accept it

### ISSUE THREAD

**Issue by ccagrawal** [charlie86/spotifyr#39]
I installed the latest development version using devtools, and I am unable to run get_playlist_audio_features:

`get_playlist_audio_features(user, playlists$playlist_uri)`
` Error in get_playlists(username, playlist_uris, show_progress = show_progress) : 
  unused argument (show_progress = show_progress)`

I believe this is because it passes the _show_progress_ parameter to _get_playlists_ and _get_playlist_tracks_, two functions that do not use that parameter.

**Comment by charlie86** [comment]
woops! Just fixed, thanks for pointing this out!
