### ISSUE TITLE
Access Token not always passed when functions call each other

### ISSUE THREAD

**Issue by ccagrawal** [charlie86/spotifyr#40]
Suppose I'm in an environment where I cannot modify my variables the same way you do in your example for adding the API keys. Then I manually pass the access token to some functions. However, some of the functions call other functions in the library, but they don't pass the access token. Then those other functions don't work.

Some examples:

* _get_user_playlists_ doesn't pass it to _get_user_playlist_count_
* _get_playlist_audio_features_ doesn't pass it to _get_playlists_
* _get_playlist_audio_features_ doesn't pass it to _get_playlist_tracks_
* _get_playlist_audio_features_ doesn't pass it to _get_track_popularity_
* _get_playlist_audio_features_ doesn't pass it to _get_track_audio_features_

I understand most people probably just set the environment variables the way you showed in the example, so this isn't critical for you. Whenever I find other examples, I can add them here so you can fix quickly whenever you get time.

**Comment by ccagrawal** [comment]
Kind of related -- you can make the parallelize parameters pass as well.

For example, right now _get_playlist_tracks_ has parallelize = TRUE by default, and _get_playlist_audio_features_ calls this function without giving the ability for me to set parallelize = FALSE.

So two quick fixes could be to set parallelize to FALSE by default in _get_playlist_tracks_ (due to the SSL certificate issue), and add a parallelize parameter to _get_playlist_audio_features that is passed to _get_playlist_tracks_.

**Comment by charlie86** [comment]
@ccagrawal Really appreciate you pointing this out! Just fixed the ones you've listed and a few more I found. Were you experiencing the SSL cert error? If so I'd love to know if this fixed it - I can't reliably reproduce it.

**Comment by ccagrawal** [comment]
Yes, I was experiencing the SSL certificate error, and this did fix it.

I'll try reproducing the error again later this week, and I'll see if I can pinpoint the cause.

**Comment by charlie86** [comment]
@ccagrawal thanks!
