### ISSUE TITLE
Setting up Dev account on Spotify

### ISSUE THREAD

**Issue by chris-billingham** [charlie86/spotifyr#41]
Hiya,

Really struggling to get the dev account set up properly on Spotify and was wondering whether there was a particular way of setting it up.

I've got through the process and everything seems ok on the dashboard but I get this error:
`> beatles <- get_artist_audio_features('the beatles')
Error in get_spotify_access_token() : 
  Could not authenticate with given Spotify credentials:
Invalid client`

Can you help?

**Comment by charlie86** [comment]
Hey Chris. By default, `get_artist_audio_features()` calls `get_spotify_access_token()` and looks for the environment variables `SPOTIFY_CLIENT_ID` and `SPOTIFY_CLIENT_SECRET`. Have you set those? If so, you should see your credentials by running `Sys.getenv("SPOTIFY_CLIENT_ID")` and `Sys.getenv("SPOTIFY_CLIENT_SECRET")`
