### ISSUE TITLE
solving authentication issues

### ISSUE THREAD

**Issue by MCWillemsen** [charlie86/spotifyr#42]
I had some trouble getting the authentication to work, until I found out the I need to set the return URL explicitly in my WebApp (http://localhost:1410/). Might be helpful to add that to the instructions.

**Comment by charlie86** [comment]
@MCWillemsen Thanks for pointing this out! Are you referring to `get_spotify_authorization_code()`?

**Comment by ahdvnd** [comment]
@MCWillemsen How did you actually set the return URL? When I run the command `get_spotify_authorization_code()` I get to a page that says `INVALID_CLIENT: Invalid redirect URI`.

**Comment by MCWillemsen** [comment]
I use http://localhost:1410/ and that seems to work well.

Martijn

**Comment by ahdvnd** [comment]
Ah thanks. It works for me now.

**Comment by bczernecki** [comment]
Had this same problem. 
Precisely the URL is: https://developer.spotify.com/dashboard/applications/ 
and then you can change in your dashboard

**Comment by Ostrensky** [comment]
I am having the same error ("Error: Must enter a valid uri") in some functions of the package (get_album_data, get_discography...). I tried everything related to the "Redirect URI", but still not works.

**Comment by zhiiiyang** [comment]
@MCWillemsen Thank you for providing the answer. I have been looking for it for the last hour and yours works perfectly: just use http://localhost:1410/.

**Comment by charlie86** [comment]
thanks everyone - I've added this to the readme

**Comment by sillasgonzaga** [comment]
What happens if I keep getting the Illegal scope error after adding this localhost?

**Comment by dtdoering** [comment]
Hey @sillasgonzaga, I was getting perhaps the same issue as you: I initially installed the CRAN version, and then would get redirected to a blank Chrome tab with the text "Illegal scope" after calling `spotifyr::get_spotify_authorization_code()`, *even after adding the localhost setting to my Spotify settings*.

What fixed it for me was simply just restarting my R session, ensuring the Dev version of `spotifyr` was installed, and trying again!

Hope that helps.

**Comment by speegled** [comment]
I had the same issue as @sillasgonzaga and it was fixed by installing the dev version, as suggested by @dtdoering. Thanks!
