### ISSUE TITLE
Add Copyright Information to get_artist_albums

### ISSUE THREAD

**Issue by Tom-Wolff** [charlie86/spotifyr#45]
I'm hoping to look at the record labels associated with each album released by an artist. This information is contained under "copyrights" in the JSON. Is there any way to have `get_artist_albums` return a column containing a string of the copyright info for each album? I'd greatly appreciate it if the function would provide that information.

Thanks.

**Comment by Phippsy** [comment]
Hi -  I created a function which may help with this. Since `get_albums()` is deprecated, I made this as a temporary workaround. 
Cheers.

**Example**

```r
# https://developer.spotify.com/documentation/web-api/reference/object-model/#copyright-object
radio_albums <- get_artist_albums(artist = "Radiohead")
radio_meta <- get_album_meta(albums = radio_albums$album_uri)
radio_album_copyright <- radio_meta %>%
    mutate(uri = str_replace(uri, "spotify:album:", "")) %>% 
    dplyr::left_join(radio_albums, by = c("uri" = "album_uri")) %>%
    select(album_name, contains("copyright"))
```

**Source code for working function**
```r
#' Get album metadata, including genre and copyright information
#'
#' @param albums A character vector containing the ids of one or several albums to retrieve information for
#' @param access_token Spotify Web API token. Defaults to spotifyr::get_spotify_access_token()
#'
#' @return
#' Returns a data frame of results containing album data
#' @export
#'
#' @examples
get_album_meta <- function(albums = character(), access_token = get_spotify_access_token()) {

    url <- 'https://api.spotify.com/v1/albums'

    content <- RETRY('GET', url,
                     query = list(ids = paste0(albums, collapse = ","),
                                  access_token = access_token),
                     encode = "json") %>% content()

    res <- map_df(1:length(content$albums),
                  ~ tibble(uri = content$albums[[.x]][["uri"]],
                             type = content$albums[[.x]][["album_type"]],
                           copyright_text = unlist(map(content$albums[[.x]][["copyrights"]], "text")),
                           copyright_type = unlist(map(content$albums[[.x]][["copyrights"]], "type")),
                             genres = unlist(ifelse(length(content$albums[[.x]][["genres"]]) == 0, "", content$albums[[.x]][["genres"]])))) %>%
        mutate(copyright_type = paste0("copyright_type_", copyright_type)) %>%
        spread(key = copyright_type, value = copyright_text)

    return(res)
}
```

**Comment by Tom-Wolff** [comment]
Works great! Thanks.

**Comment by charlie86** [comment]
@Tom-Wolff I just merged that add from @Phippsy with one small change - `get_album_meta()` is now `get_albums()`

**Comment by Tom-Wolff** [comment]
Thanks for this! I just tested this out, and it's working for the most part. For whatever reason, though, I get the message `Request failed [400].` when trying to collect the labels for albums of certain artists. Here's a quick example of an artist that's causing the problem:

`MG <- get_artist_albums(artist = "The Mountain Goats")
MG_labels <- get_albums(albums = MG$album_uri)`

Any thoughts on what's going on here?

**Comment by charlie86** [comment]
@Tom-Wolff thanks for catching this! I just pushed a fix. 

@Phippsy FYI, it looks like the API has a limit of 20 album uris at once, so I added a loop to batch calls to the album endpoint in groups of 20

**Comment by Phippsy** [comment]
@charlie86 Nice one - cheers for that!

**Comment by Tom-Wolff** [comment]
This is great! I've been trying to figure out what was going on over the last few days and it's been having me scratch my head.

If it's any help, I also wrote these functions based on @Phippsy 's code above. They return the 50 most relevant search results for artists/albums in a record label. Is there any chance  I could add the same looping/batch call fix to these? Let me know. (I'm still pretty new to GitHub, so I don't know if there's a better way to post this.) 

`get_label_artists <- function(label = character(), type = 'artist', access_token = get_spotify_access_token()) {
  
  url <- 'https://api.spotify.com/v1/search'
  
  content <- RETRY('GET', url,
                   query = list(q = paste0('label:"', label, '"', sep = '', collapse = ","),
                                type = type,
                                limit = 50,
                                access_token = access_token),
                   encode = "json") %>% content()
  
  res <- map_df(1:length(content$artists$items),
                ~ tibble(
                  artist = content$artists$items[[.x]]$name,
                  label = label,
                  genres = paste(unlist(content$artists$items[[.x]]$genres), collapse = ', '),
                  popularity = content$artists$items[[.x]]$popularity,
                  follower_count = content$artists$items[[.x]]$followers$total,
                  artist_uri = str_replace(content$artists$items[[.x]]$uri, 'spotify:artist:', ''),
                  artist_image_url_big = content$artists$items[[.x]]$images[[1]]$url,
                  artist_image_url_small = content$artists$items[[.x]]$images[[2]]$url
                  ))

  return(res)
}`

`get_label_albums <- function(label = character(), album_types = 'album', access_token = get_spotify_access_token()) {
  
  url <- 'https://api.spotify.com/v1/search'
  
  content <- RETRY('GET', url,
                   query = list(q = paste0('label:"', label, '"', sep = '', collapse = ","),
                                type = album_types,
                                limit = 50,
                                access_token = access_token),
                   encode = "json") %>% content()
  
  res <- map_df(1:length(content$albums$items),
                ~ tibble(
                        artist = content$albums$items[[.x]]$artists[[1]]$name,
                        album = content$albums$items[[.x]]$name,
                        type = content$albums$items[[.x]]$type,
                        label = label,
                        release_date = content$albums$items[[.x]]$release_date,
                        artist_uri = str_replace(content$albums$items[[.x]]$artists[[1]]$uri, "spotify:artist:", ''),
                        album_uri = str_replace(content$albums$items[[.x]]$uri, "spotify:album:", ''))
                        )
  
  return(res)
}`

**Comment by charlie86** [comment]
@Tom-Wolff awesome stuff! I just added these in with some minor tweaks, along with `get_genre_artists()`. Do you have a preferred email to be cited in the package description?

**Comment by Tom-Wolff** [comment]
tom.wolff@duke.edu should do it. Thanks for adding it in! I'm excited to play around with the genre artists search, too!
