### ISSUE TITLE
Artists column names inconsistency across functions

### ISSUE THREAD

**Issue by dinhani** [charlie86/spotifyr#48]
The column names in the dataframe returned by `get_artists` , `get_genre_artists` and `get_label_artists` are inconsistent.

In the first function, there are columns named `artist_genres`, `artist_popularity` and `artist_num_followers`, while in the last two function the same values are named `genres`, `popularity`  and `follower_count`.

**Comment by charlie86** [comment]
@dinhani I've just pushed some updates that standardized most of the names to whatever is returned from the API
