### ISSUE TITLE
get_user_playlists does not return all playlists

### ISSUE THREAD

**Issue by mpettis** [charlie86/spotifyr#50]
This function does not return all of my playlists.  I can go to the Spotify browser player and get playlist IDs and hardcode them into my script when I want to retrieve their contents, but I don't know why the playlist isn't returned as part of the `get_user_playlists` function.  Is there some limit going on?  Can we configure that limit as a function argument.

Thanks for this package and the work.

**Comment by msmith7161** [comment]
I'm having a similar issue! Trying to get all the songs on Spotify's "Viva Latino" and "Baila Reggaeton" playlists, both public and very popular. When I use get_user_playlists with the username "spotify" it returns 389 entries but the two I'm looking for don't appear. Is there any way I can specifically search for those two playlists?

**Comment by charlie86** [comment]
@msmith7161 Thanks for the examples. I see Viva Latino, but it is odd that Baila Reggaeton doesn't show up. It does look like you can access it directly using the spotify uri, which you can find from the desktop app.

![image](https://user-images.githubusercontent.com/9537903/50762862-75965600-126e-11e9-994b-8d92ea2462b3.png)


```
spotify_playlists <- get_user_playlists('spotify')

spotify_playlists %>% 
    filter(playlist_name %in% c('¡Viva Latino!', 'Baila Reggaeton'))

### look up "Baila Reggateon" by uri - can found from within spotify desktop app
get_playlists('spotify', '37i9dQZF1DWY7IeIP1cdjF')
```

Let me know if that helps!
