### ISSUE TITLE
copywrite error in `get_artist_audio_features()`

### ISSUE THREAD

**Issue by charlie86** [charlie86/spotifyr#51]
`Error: Columns `copyright_text`, `copyright_type` must be 1d atomic vectors or lists`

**Comment by erdavis1** [comment]
Hello,

Get_artist_audio_features is erroring out on certain artists. This happens whether I search by artist uri or by artist name. Any chance my error message is related to this issue?

The error message:
Error: All columns in a tibble must be 1d or 2d objects:
* Column `copyright_text` is NULL
* Column `copyright_type` is NULL

Examples:
get_artist_audio_features('00DSeUAdyYqUyGFqeySG68') 
get_artist_audio_features('ohGr') 

get_artist_audio_features('4tM8qmqg5cEZPHNLNQwHeb') 
get_artist_audio_features('Megaherz')

**Comment by charlie86** [comment]
@erdavis1 thanks for pointing this out! This is now fixed
