### ISSUE TITLE
Error with get_albums()

### ISSUE THREAD

**Issue by AlbertoAlmuinha** [charlie86/spotifyr#53]
I tried the next code:

album<-list()

for (i in 1:length(artist_uri)) {         
       album[[i]]<-get_albums(artist_uri[i], access_token)
 }

and I get the next error:

Error in albums$error : $ operator is invalid for atomic vectors

What's the problem??

**Comment by charlie86** [comment]
@AlbertoAlmuinha Do you have an example of the actual albums/album uri list you're using? That error may indicate a rate limiting issue, but it's hard to tell without a reproducible example
