### ISSUE TITLE
get_my functions are not found

### ISSUE THREAD

**Issue by sarcuzz** [charlie86/spotifyr#54]
> get_my_top_tracks(time_range = 'short_term', limit = 5) %>% 
+   select(track_name, artist_name, album_name) %>% 
+   kable()
Error in get_my_top_tracks(time_range = "short_term", limit = 5) : 
  could not find function "get_my_top_tracks"

**Comment by charlie86** [comment]
@sarcuzz Are you using the github or CRAN version? The CRAN version is pretty outdated at the moment. To install the github version, try devtools::install_github("charlie86/spotifyr")

Let me know if that doesn't work
