### ISSUE TITLE
Error: Identified global objects via static code inspection

### ISSUE THREAD

**Issue by ShanSabri** [charlie86/spotifyr#55]
### Goal

I am writing up a small project where I'm trying to broadcast/tweet any edits to a public and collaborative Spotify playlist. These edits can be song additions or song deletions. I am using `spotifyr` to grab Spotify playlist data and using `rtweet` to tweet edits of the given playlist. I have posted code below that achieves this. The goal is to have this code running on a server for long periods of time (order of days to months). 

### Problem

The problem I seem to be running into is an error that sporadically appears, after several hours from what I've noticed. This error will appear even if there are no updates to the playlist. I've posted the error below: 

```r
Error: Identified global objects via static code inspection (function (this_playlist); {; print(this_playlist); num_loops <- ceiling(playlists$playlist_num_tracks[this_playlist]/100); map_df(1:num_loops, function(this_loop) {; print(this_loop); ...; }; }); }). $ operator is invalid for atomic vectors
``` 

I assume that the problem here has something to do with calling `get_playlist_tracks()` many times since I've wrapped this function in a repeat loop. Perhaps there is limited number of queries that can be made? [Line 295 of playlists.R](https://github.com/charlie86/spotifyr/blob/cb7b1c4ee31622c9e084125d991c7df7413c2e45/R/playlists.R#L295) seems to suggest that a retry is requested until it succeeds but the number of succeeds are limited to 50? I'm wondering if there would be anyway around this, or a better way to go about this?

### Code
``` r
## INIT GRAB PLAYLIST INFO 
usr <- "MyUserName"
playlist <- "MyPlaylist"
usr_playlists <- get_user_playlists(usr)
playlist_tracks <- get_playlist_tracks(usr_playlists[usr_playlists$playlist_name == playlist,], 
                                                      parallelize = TRUE, 
                                                      future_plan = "multiprocess")
init_n_tracks <- nrow(playlist_tracks) 


## CHECK FOR ANY EDITS
## IF EDITS THEN TWEET
repeat{
  upd <- get_playlist_tracks(usr_playlists[usr_playlists$playlist_name == playlist,], 
                                          parallelize = TRUE, 
                                          future_plan = "multiprocess")
  n_tracks <- nrow(upd)
  if(n_tracks  != init_n_tracks){ 
    ids <- c("playlist_name", "playlist_img", "track_name", "track_uri", 
             "artist_name", "album_name", "album_img", "track_added_at")
    if(n_tracks > init_n_tracks){
      change_lab <- "Added:"  
      change <- anti_join(upd, playlist_tracks, by = ids)
    } else {
      change_lab <- "Removed:"
      change <- anti_join(playlist_tracks, upd, by = ids)
    }
    tweet <- paste(format(Sys.time(), "%a %b %d %X"), 
                   change_lab, 
                   change$track_name,
                   "by", 
                   change$artist_name)
    
    tweet <- substr(tweet, 1, 139)
    post_tweet(tweet)
    init_n_tracks <- n_tracks
    playlist_tracks <- upd
  }
}
```

### rtweet version
``` r
> packageVersion("rtweet")
[1] ‘0.6.8.9000’

> packageVersion("spotifyr")
[1] ‘1.1.0’
```

<details><summary>Session info</summary>
<p>

``` r
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.3.0     stringr_1.3.1     dplyr_0.7.8       purrr_0.2.5       readr_1.1.1       tidyr_0.8.2       tibble_1.4.2     
 [8] ggplot2_3.1.0     tidyverse_1.2.1   rtweet_0.6.8.9000 spotifyr_1.1.0   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       cellranger_1.1.0 plyr_1.8.4       pillar_1.3.0     compiler_3.5.1   bindr_0.1.1      tools_3.5.1     
 [8] digest_0.6.18    gtable_0.2.0     lattice_0.20-38  nlme_3.1-137     lubridate_1.7.4  jsonlite_1.5     pkgconfig_2.0.2 
[15] rlang_0.3.0.1    cli_1.0.1        rstudioapi_0.8   yaml_2.2.0       parallel_3.5.1   haven_1.1.2      bindrcpp_0.2.2  
[22] withr_2.1.2      furrr_0.1.0      httr_1.3.1       xml2_1.2.0       globals_0.12.4   hms_0.4.2        grid_3.5.1      
[29] tidyselect_0.2.5 glue_1.3.0       listenv_0.7.0    R6_2.3.0         readxl_1.1.0     modelr_0.1.2     magrittr_1.5    
[36] scales_1.0.0     backports_1.1.2  codetools_0.2-15 assertthat_0.2.0 rvest_0.3.2      colorspace_1.3-2 future_1.10.0   
[43] stringi_1.2.4    lazyeval_0.2.1   munsell_0.5.0    broom_0.5.0      crayon_1.3.4   
```

</p>
</details>

**Comment by charlie86** [comment]
@ShanSabri Hmm, very interesting. That sounds like a really cool project! I think it's likely a rate limiting issue. I see two potential fixes:

1. Currently the `RETRY` call is set to 10 - have you tried forking or making your own version of the function with a higher number?

2. Running in parallel will increase speed slightly but is definitely prone to more rate limiting issues, especially if running constantly. Have you tried running without parallelization?

Let me know if that makes sense!

**Comment by ShanSabri** [comment]
I am now running without parallelization and will see if I continue to see this error. Regarding your first point, I will fork the repo if I can't seem to get anything else to work. Thanks!

**Comment by charlie86** [comment]
@ShanSabri I'm hesitant to make that the default, but maybe it could be another parameter. Have you tried that yourself?

**Comment by charlie86** [comment]
Closing this for now, since there aren't any action items on my end
