### ISSUE TITLE
get_track_audio_analysis() function not found

### ISSUE THREAD

**Issue by samotleriche** [charlie86/spotifyr#56]
It seems that several of the functions aren't being found. Any Idea why? 
Error in get_track_audio_analysis() : 
  could not find function "get_track_audio_analysis"

**Comment by charlie86** [comment]
@samotleriche Are you using the github or CRAN version? The CRAN version is pretty outdated at the moment. To install the github version, try `devtools::install_github("charlie86/spotifyr")`

Let me know if that doesn't work
