### ISSUE TITLE
when I try to use 'get_user_playlists' with my spotify_id I have this error: Error in txtProgressBar(min = 0, max = num_loops, style = 3) : must have 'max' > 'min'

### ISSUE THREAD

**Issue by dpbac** [charlie86/spotifyr#58]
When I try to use 'get_user_playlists' with my spotify_id I have this error: Error in txtProgressBar(min = 0, max = num_loops, style = 3) : must have 'max' > 'min'.

I've tried with another id and it worked. I'm using the github version. Any idea how I can make it work?

Thanks!

**Comment by charlie86** [comment]
@dpbac Thanks for pointing this out! I've seen this before if the user doesn't have any public playlists. Would you mind sharing your id so I can test it out?
