### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by aml969** [charlie86/spotifyr#6]
This was all working fine for me Nov. 2nd, but I went back to my script and seems like I get this error in every function I try. Not sure if it's a bug or on my end. Do you know what could be going on? Thanks

```
devtools::install_github('charlie86/spotifyr')
library(spotifyr)
Sys.setenv(SPOTIFY_CLIENT_ID = 'xxxxxxxxxxxxxxxxxxxxx')
Sys.setenv(SPOTIFY_CLIENT_SECRET = 'xxxxxxxxxxxxxxxxxxxxx')

access_token <- get_spotify_access_token()

beatles <- get_artist_audio_features('the beatles')
#Error in res$error : $ operator is invalid for atomic vectors

get_artists('radiohead')
#Error in res$error : $ operator is invalid for atomic vectors
```

**Comment by charlie86** [comment]
hmm, I'm not able to reproduce this unfortunately. Have you tried stepping through the raw code from one of the functions? Take get_artists(), for example since it's smaller:

function (artist_name, access_token = get_spotify_access_token()) 
{
    res <- GET("https://api.spotify.com/v1/search", query = list(q = artist_name, 
        type = "artist", access_token = access_token)) %>% content
    if (!is.null(res$error)) {
        stop(paste0(res$error$message, " (", res$error$status, 
            ")"))
    }
    content <- res$artists %>% .$items
    artists <- map_df(seq_len(length(content)), function(this_row) {
        this_artist <- content[[this_row]]
        list(artist_name = this_artist$name, artist_uri = gsub("spotify:artist:", 
            "", this_artist$uri), artist_img = ifelse(length(this_artist$images) > 
            0, this_artist$images[[1]]$url, NA))
    }) %>% dplyr::filter(!duplicated(tolower(artist_name)))
    return(artists)
}

**Comment by charlie86** [comment]
It looks like your error is happening way at the top. What do you get if you just run the following:
```
artist_name <- 'the beatles'
access_token <- get_spotify_access_token()

res <- GET("https://api.spotify.com/v1/search", query = list(q = artist_name, 
        type = "artist", access_token = access_token)) %>% content
res
```

**Comment by aml969** [comment]
Hey thanks for the reply. I did try stepping through a different function, but get_artists() did the trick as it was a little clearer. It seemed like for whatever reason tidyverse and httr were not loaded. Could've sworn I didn't have that problem with dependencies before, but I must have had them loaded from a previous session last time. Thanks again for the help. Great package, by the way.

**Comment by josephquinn** [comment]
I'm having a similar issue. Which is quite odd, because the results aren't consistently reproducible for me. I run the following function (a modified version of get_artist_audio_features() that does not require confirm the name of the artist each time I make a request):

```
artistFeatureGrab <- function(musician){
  
  artists         <- get_artists(musician) #pulls tbl of all potential artist matches
  selected_artist <- artists$artist_name[1] #confirms that the first artist name in the list is the right one
  artist_uri      <- artists$artist_uri[artists$artist_name == selected_artist] #gets URI for the selected artist
  albums          <- get_albums(artist_uri) #get a list of the albums for each artist

  #checks to make sure this list shows at least one album, or returns else condition message
    if (nrow(albums) > 0) {
    
      albums <- select(albums, -c(base_album_name, base_album, num_albums, num_base_albums, album_rank))
      
  } else {
    
    return(paste0("Cannot find any albums for \"", selected_artist, "\" on Spotify"))
    
    }

  #grab the data you want for each album and its tracks
  album_popularity <- get_album_popularity(albums)
  tracks           <- get_album_tracks(albums)
  track_features   <- get_track_audio_features(tracks)
  track_popularity <- get_track_popularity(tracks)

  tots <- albums %>% 
    left_join(album_popularity, by = "album_uri")  %>%
    left_join(tracks,           by = "album_name") %>% 
    left_join(track_features,   by = "track_uri")  %>% 
    left_join(track_popularity, by = "track_uri")
}
```

...and run it within this for loop, which gets the features for all top 100 billboard artists in 2017:

```
top_artist_data <- as.data.frame(NULL)
for(i in 1:length(top100artists)){
  artist_data     <- artistFeatureGrab(top100artists[i]) #grab songs from artist as data frame
  this_artist      <- rep.int(top100artists[i], nrow(artist_data)) #create a name vector as long as artist_data
  add_artist_data <- cbind(this_artist, artist_data) #combine 
  top_artist_data <- rbind(top_artist_data, add_artist_data) #stack
  print(this_artist[1])
}
```

Every time I run the program, I get the following error and traceback after the first few loops. Sometimes the loop runs through "Drake" (top100artists[2]; other times it runs as far as "U2" (top100artists[18]). There doesn't seem to be much rhyme or reason to how far the loop will run before breaking.

```
Error: $ operator is invalid for atomic vectors 
5.
.f(.x[[i]], ...) 
4.
map(.x, .f, ...) 
3.
map_df(1:length(albums$items), function(this_row) {
    this_album <- albums$items[[this_row]]
    if (this_album$album_type == "album" & gsub("spotify:artist:", 
        "", this_album$artists[[1]]$uri) == artist_uri) { ... 
2.
get_albums(uri) 
1.
artistFeatureGrab(top100artists[i])
```

Any thoughts? Regardless, thanks for the great package and blog. I'll be sure to cite you if I get anywhere with my efforts!

**Comment by Lef-F** [comment]
Similarly to @josephquinn, with the development version of the package, I use `get_artist_audio_features` in a for loop for multiple artists and I get the following warning:

```
Warning message:
In artists$artist_name == selected_artist :
  longer object length is not a multiple of shorter object length
```

Although it is a warning, I don't get any output from `get_artist_audio_features` when this occurs.

Sample code:
```
artists <- c("Pink Floyd","Radiohead", "Porcupine Tree", "Metallica", "Dream Theater")
spotify_data <- data.frame()
for (artist in artists) {
    spotify_data <- rbind(spotify_data, data.frame(get_artist_audio_features(artist_name = artist)))
}
```

**Comment by charlie86** [comment]
Thanks for the examples, @Lef-F @josephquinn! I think there are two issues going on.

1. The warning message ```In artists$artist_name == selected_artist :
  longer object length is not a multiple of shorter object length``` is due to a bug in how `return_closest_artist` was implemented. It uses string distance to find the most similar artist name, which allowed for multiple artists to be returned for the same query (in your case, there's a band called "Floyd Pink" that also got flagged along with the real band haha). This is fixed to now return whichever ranked higher in spotify's search API in the event of a tie (I verified that "Pink Floyd" is now returned).

2. For the `$ operator is invalid for atomic vectors` error, I've seen this pop up a few times and am really not sure what's going on - as you've also found it's not consistently reproducible. My hunch is that it's somehow related to API rate limiting or connection issues. Have you tried adding a Sys.sleep() in your loop?

**Comment by Lef-F** [comment]
Thanks for taking the time @charlie86! I just tried `Sys.sleep()` but it keeps missing Pink Floyd now and it gives me the following output with a warning:
```
Selecting artist "Pink Floyd". Choose return_closest_artist = FALSE to interactively choose from all the artist matches on Spotify.Selecting artist "Floyd Pink". Choose return_closest_artist = FALSE to interactively choose from all the artist matches on Spotify.
Warning:
 simpleWarning in artists$artist_name == selected_artist: longer object length is not a multiple of shorter object length
```

I suspect that this could be solved by replacing `==` with `%in%` maybe? What do you think?

**Sample Code:**
```
artists <- c("Pink Floyd","Radiohead", "Porcupine Tree", "Metallica", "Dream Theater")

spotify_data <- data.frame()
for (artist in artists) {
  tryCatch({
    Sys.sleep(5)
    spotify_data <- rbind(spotify_data, data.frame(get_artist_audio_features(artist_name = artist)))
  }, 
  error = function(e){
    cat("Error with artist", artist, "\n", unlist(e), "\nTrying again...\n")
    Sys.sleep(10)
    spotify_data <- rbind(spotify_data, data.frame(get_artist_audio_features(artist_name = artist)))
  },
  warning = function(w){
    cat("Warning:\n", toString(w), "\nTrying again...\n")
    Sys.sleep(10)
    spotify_data <- rbind(spotify_data, data.frame(get_artist_audio_features(artist_name = artist)))
  },
  finally = cat("Done with", artist, "\n")
  )
}
```

**Comment by charlie86** [comment]
@Lef-F Sure thing! Really appreciate you pointing out these bugs. Have you tried installing the latest from github? I just pushed an update last night.

**Comment by Lef-F** [comment]
@charlie86 I didn't notice! I just updated and the code in my previous post now runs without any errors or warnings **even without `Sys.sleep()`**!!!! 😮 🍻 
Thanks a bunch!

**Comment by josephquinn** [comment]
The updates work well @charlie86 - thanks a lot! One issue I'll point you to, which may be idiosyncratic on my end. When I tried to reinstall from github, I got this error:

```
ERROR: dependency 'lubridate' is not available for package 'spotifyr'
* removing 'C:/Users/jmq4/Documents/R/win-library/3.4/spotifyr'
Installation failed: Command failed (1)
> library(lubridate)
Error in library(lubridate) : there is no package called ‘lubridate’
> install.packages("lubridate")
Error in install.packages : Updating loaded packages
```
I installed lubridate independently, was prompted to restart RStudio after running install.packages("lubridate"), did so, ran the lubridate library, then tried to install spotifyr again. It worked after those steps.

Thanks again!
