### ISSUE TITLE
Authenticating multiple or family accounts? 

### ISSUE THREAD

**Issue by thedrewwalker** [charlie86/spotifyr#60]
Is this possible? I'm relatively new to R and OAuth but wondering if anyone knew of a way?

**Comment by charlie86** [comment]
@thedrewwalker I'm not sure what you mean. You should be able to authenticate with any valid account, but if you want data from multiple accounts you'd need to pull data separately.

**Comment by thedrewwalker** [comment]
@charlie86 I'm basically trying to write code to pull recently played audio features for 5 different accounts. Are you saying I should make a separate script for each account? I'm not sure how I can do this without all of the scripts using the information from the first account I authenticate. I guess I'm not sure how to authenticate new accounts

**Comment by charlie86** [comment]
@thedrewwalker You could use the same script, but yes, you'd have to loop through each of the 5 accounts, passing a different authentication token for each one. The issue is that only one account can be logged in at a time within an API call.

I haven't tried this myself, but I think something like this would work:

```
client_id_1 <- 'xxxxxxxx'
client_secret_1 <- 'xxxxxxx'

client_id_2 <- 'yyyyyyyy'
client_secret_2 <- 'yyyyyyy'

auth_code_1 <- get_spotify_authorization_code(client_id = client_id_1, client_secret = client_secret_1)
auth_code_2 <- get_spotify_authorization_code(client_id = client_id_2, client_secret = client_secret_2)

recently_played_1 <- get_my_recently_played(authorization = auth_code_1)
recently_played_2 <- get_my_recently_played(authorization = auth_code_2)
```
