### ISSUE TITLE
Access resources using URI's instead of names?

### ISSUE THREAD

**Issue by thomas-kahn** [charlie86/spotifyr#62]
How do I access artists or other resources from the Spotify API using URI's instead of names, titles etc.? It would be great if this was added to the documentation somewhere.

Thanks for making this library for r! It's really fun to play with!

**Comment by charlie86** [comment]
@thomas-kahn this is an excellent idea! I've been working on this for a while now, I'll let you know when it's done!

**Comment by charlie86** [comment]
@thomas-kahn I just pushed a bunch of updates that use the Spotify ids instead of names

**Comment by thomas-kahn** [comment]
That is excellent news! Thanks a million for this improvement!
