### ISSUE TITLE
Add playlist song release date

### ISSUE THREAD

**Issue by Dantesean** [charlie86/spotifyr#63]
I have found no way to directly get song release dates for playlists. I had to create a quiet complex way to actually find it (see added code).

Is there a way to get info on that as well?

`get_release_date <- function(track_name, artist_name, album_name) {
  if(nrow(get_tracks(track_name = track_name, artist_name = artist_name, album_name = album_name, return_closest_track = TRUE)) == 0){
    get_albums(get_tracks(track_name = track_name, artist_name = artist_name, return_closest_track = TRUE)$album_id)$release_date
  } else {
    get_albums(get_tracks(track_name = track_name, artist_name = artist_name, album_name = album_name, return_closest_track = TRUE)$album_id)$release_date
  }
}`

**Comment by charlie86** [comment]
@Dantesean Unfortunately this would require a bunch of additional calls to include this in the `get_playlist_` functions, so I'd say this would be something that should be done manually. But, using the redesigned `get_tracks()` should make it easier:

```
playlist_id <- search_spotify('rapcaviar', 'playlist') %>% 
    slice(1) %>% 
    pull(id)

playlist_tracks <- get_playlist_tracks(playlist_id)

track_release_dates <- get_tracks(playlist_tracks$track.id) %>% 
    select(id, album.release_date)

playlist_tracks %>% 
    left_join(track_release_dates, by = c('track.id' = 'id'))

```

Let me know if you have any questions!
