### ISSUE TITLE
get_playlist_audio_features() deleted

### ISSUE THREAD

**Issue by jaburgoyne** [charlie86/spotifyr#64]
In the most recent commit, get_playlist_audio_features() was deleted, and there doesn't seem to be an obvious replacement. Similar aggregating functions still  remain, e.g., get_artist_audio_features(). Was this intentional, or was it an accident?

**Comment by charlie86** [comment]
@jaburgoyne this was intentional, but it will be added back in soon

**Comment by charlie86** [comment]
just added it back!

**Comment by jaburgoyne** [comment]
It actually isn't back yet – some other playlist functions are, but not get_playlist_audio_features(). :) If that's a design choice, obviously that's up to you, but my students and I found this particular function very helpful. It lets you plan your corpus with the Spotify interface – often easiest – and then pull down everything efficiently into R once you're happy with your playlist.

**Comment by charlie86** [comment]
@jaburgoyne woops! Thanks for letting me know, I just added it back, but the fields have changed a bit.

**Comment by charlie86** [comment]
Let me know if there's anything you were used to using that I can try to add back in!

**Comment by jaburgoyne** [comment]
Thanks! There is a bug in the new version in line 321: 

Error in eval(parse(text = text, keep.source = FALSE), envir) : 
  object 'tmp' not found

**Comment by jaburgoyne** [comment]
And this function was the only big one that we were missing in the update. I have a few ideas for enhancements surrounding a more structured response from get_audio_analysis(), but I haven't yet fully convinced myself what the best way to do it is even just for me, let alone for the general case of a CRAN package.

**Comment by charlie86** [comment]
@jaburgoyne Thanks for pointing that out! Just pushed a fix.

I totally hear you on the audio analysis object. I'm working on a project that uses data from it, and I'll include an example of how I think it can be used. I think it might be really tough to get a generic use case down, but I'm definitely open to suggestions.

**Comment by spacecat20** [comment]
Hi,

I'm quite new at this, so I may be overlooking something obvious, but the get_playlist_audio_features doesn't seem to be there still, though by your conversation above, it should be. The package is freshly updated and I reloaded the library after, but I am still getting "could not find function "get_playlist_audio_features"

Am I missing something?
