### ISSUE TITLE
Call geniusR functions from `genius` namespace.

### ISSUE THREAD

**Issue by JosiahParry** [charlie86/spotifyr#65]
Hey Charlie,

Update: `geniusR` is now officially `genius` and is available on CRAN. The genius functions have been refactored since integration into spotifyr providing things such as the musicians for each verse, handling instrumental tracks, etc. Can we integrate genius into the spotifyr?

**Comment by charlie86** [comment]
Hey, congrats! That's awesome to hear. Let's do it - assuming the idea is then that we pull the existing `geniusR` stuff out of `spotifyr`?

**Comment by charlie86** [comment]
@JosiahParry just added genius as an import. Everything seems to be working, let me know if you get a chance to check it out, and I'll push and update to CRAN

**Comment by JosiahParry** [comment]
Awesome. I'll pull and check tomorrow (Friday 3/9)
