### ISSUE TITLE
In `get_artist_audio_features` please set `limit` to the max in the call to `get_album_tracks`

### ISSUE THREAD

**Issue by moodymudskipper** [charlie86/spotifyr#66]
It's now set to 20, and many albums have more than 20 tracks so we can easily miss some without noticing.

Thanks for the good work.

**Comment by charlie86** [comment]
@moodymudskipper thanks for pointing this out! have you tried with the lastest dev version? I pushed an update a few days ago that aimed to address this

**Comment by moodymudskipper** [comment]
Indeed with the current github version all goes fine thanks!
