### ISSUE TITLE
OAuth flow

### ISSUE THREAD

**Issue by ElTav** [charlie86/spotifyr#67]
Hello,
I'm looking to create a couple endpoints using [rplumber](https://www.rplumber.io) and spotifyr, and have an application up and running on Heroku with a couple unrelated endpoints. I'd like to do something like the following

```
#* @get /recentlyplayed
getRecentlyPlayed <- function() {
    get_my_recently_played(limit = 5) %>%
        select(track_name, artist_name, album_name, played_at_utc) %>%
        kable()
}
```

However, accessing the endpoint remotely hangs, and the Heroku logs display:

```
Waiting for authentication in browser...
2019-03-14T21:54:25.049508+00:00 app[web.1]: Press Esc/Ctrl + C to abort
2019-03-14T21:54:25.056194+00:00 app[web.1]: Please point your browser to the following url:
2019-03-14T21:54:25.057367+00:00 app[web.1]: <URL>
```

I have my `SPOTIFY_CLIENT_ID` and `SPOTIFY_CLIENT_SECRET` env vars set, and added `http://localhost:1410/` as my callback URI from the Application Dashboard as well, so I'm not sure what's going wrong. What's the best way to proceed from here?

**Comment by charlie86** [comment]
@ElTav great question! I have a similar set up, and I've been meaning to document this use case (see issue #42). When you're not able to authenticate normally on a remote machine, the trick is to authenticate locally, which will generate a `.httr_oauth` file, then upload that file to the directory on your server where the script is located. Does that make sense?
