### ISSUE TITLE
streams

### ISSUE THREAD

**Issue by tivoo** [charlie86/spotifyr#68]
Hi there!

Not sure if this is the right way to go about it since I am new here on GitHub (hi), but I was wanting to know how to be able to get streams data.

So what my wish is, is to be able to get data about the number of streams per track on an album with, say, the get_album_data function. Any way this is possible?

Cheers Timo

**Comment by charlie86** [comment]
Hey, thanks for posting! Unfortunately, that data isn't public, so we can't pull it in through the API.
