### ISSUE TITLE
Error with using get_artist_audio_features()

### ISSUE THREAD

**Issue by annafergusson** [charlie86/spotifyr#69]
I haven't seen this issue in the closed issues which might be related. 

I'm getting the error "Error in -dupe_columns : invalid argument to unary operator" when I try to run the example function `beatles <- get_artist_audio_features('the beatles')`. 

I've changed the line `select(-dupe_columns)` to `select(-one_of(dupe_columns))` and now everything is great :-)

**Comment by charlie86** [comment]
@annafergusson thanks for pointing this out! could you try to install the latest CRAN package? I believe this should be fixed.

**Comment by annafergusson** [comment]
Thanks @charlie86 - all sorted!
