### ISSUE TITLE
GetRelatedArtist? 

### ISSUE THREAD

**Issue by Leschonander** [charlie86/spotifyr#7]
Hi there,

I been using your Package for analyzing Spotify data in R and it has been very useful. However, I been meaning to pull some data from some from the API like related artists, however I am unable to do it with your R package for Spotify. I tried to do this with your package with a modified version of someone eases Spotify package and their getRelated request. Would it be possible to add a GetRelated function for you package? Code I tried at the bottom. Doesn't work because I don't know what changes I need to make the to the function to work properly. 
```
getRelated <-function(artistName, access_token = get_spotify_access_token()){
  #require(plyr)
  info<-searchArtist(artistName, token = token)
  id<-info$id[1]
  name<-info$display_name[1]

  req <- httr::GET(paste0("https://api.spotify.com/v1/artists/",id,"/related-artists"),httr::config(access_token = get_spotify_access_token())
  json1<-httr::content(req)
  M <- lapply(json1$artists, "[",
              c("name", "id", "popularity", "type" ))
  N <- lapply(json1$artists, "[[", "followers")
  N <- lapply(N, "[", "total")

  relatedArtists <- plyr::ldply(M, data.frame)
  relatedArtists$followers <- plyr::ldply(N, data.frame)$total

  return(relatedArtists)
}

```

**Comment by charlie86** [comment]
Good call! I'll work on adding a function for that when I get a chance

**Comment by charlie86** [comment]
@Leschonander I just added in the function `get_related_artists()`, and you can use either an artist name or artist uri.

```
get_related_artists('flying lotus')

get_related_artists(artist_uri = '29XOeO6KIWxGthejQqn793', use_artist_uri = TRUE)
```

Hope this is useful! Let me know if you have any questions
