### ISSUE TITLE
fields param in get_playlist_tracks

### ISSUE THREAD

**Issue by noeliaricopachon** [charlie86/spotifyr#70]
I'm trying to execute the following line:

`get_playlist_tracks('1G8IpkZKobrIlXcVPoSIuf',
                                fields = c("description", "uri"))` 

and I get a `NULL` object as response. It does not work for any other values of `fields`. I'm using this one right now because it is the one given in the documentation. 

I guess there's something wrong with the `fields` parameter cause without it the function returns the tracks properly.

**Comment by charlie86** [comment]
thanks for pointing this out!
