### ISSUE TITLE
Is there support to retrieve data from podcasts?

### ISSUE THREAD

**Issue by voltdatalab** [charlie86/spotifyr#72]

**Comment by charlie86** [comment]
@voltdatalab as far as i know, this doesn't work with the api currently

**Comment by charlie86** [comment]
@voltdatalab There are now endpoints for podcasts!

https://developer.spotify.com/community/news/2020/03/20/introducing-podcasts-api/

https://developer.spotify.com/documentation/web-api/reference/shows/
https://developer.spotify.com/documentation/web-api/reference/episodes/
