### ISSUE TITLE
Error in is.url(url) : length(url) == 1 is not TRUE

### ISSUE THREAD

**Issue by jd715** [charlie86/spotifyr#73]
When I call  `beatles <- get_artist_audio_features('the beatles')`

I receive an error:

> Error in is.url(url) : length(url) == 1 is not TRUE
In addition: Warning messages:
1: Unknown or uninitialised column: 'id'. 
2: Unknown or uninitialised column: 'name'. 

Any ideas as to why?

**Comment by johnnymdoubleu** [comment]
same result receiving. Is this because of not using the premium account?

**Comment by jd715** [comment]
I have a premium account I'm using so I don't think so

**Comment by jd715** [comment]
Amazing, thank you for the super quick update!

**Comment by suitedaces** [comment]
I was having the same issue while trying to get Kanye West's audio features, so I figured when I call kanye <- get_artist_audio_features('kanye') it works. Weird

**Comment by JosiahParry** [comment]
Development version fixed this bug. Thanks Charlie!

**Comment by merytouceda** [comment]
Hi! I downloaded the development version but I am still having this issue when i do: 

```
> my_plists_madebyme_tracks <- get_playlist_tracks(my_plists_madebyme)
Error in parse_url(url) : length(url) == 1 is not TRUE
```
