### ISSUE TITLE
search_spotify() function does not work with spaces?

### ISSUE THREAD

**Issue by saschawo** [charlie86/spotifyr#77]
Hi, thanks for your great work on the spotifyr package! I got a problem, though:

In the documentation for the search_spotify() function, there is an example for a query (under Arguments -> q):

> For example: q = "roadhouse+blues"

However, this does not return any results. Also, commands like

`search_spotify("PJ+Harvey", type = "artist")` or
`search_spotify("PJ%20Harvey", type = "artist")`

do not return any results (an empty tibble) although there is clearly a Spotify page for PJ Harvey. The `+` and `%20` are explicitly mentioned in Spotify's documentation for the API, so this should work, shouldn't it?

Thanks!

**Comment by saschawo** [comment]
I had a look at the search_spotify() function and when setting `params`, I replaced the
`q = str_replace_all(q, " ", "+")`
with
`q = q` so that no replacement of spaces is made anymore.

Now it works. Maybe, the "+" thing doesn't work (anymore) with the Spotify API?

**Comment by charlie86** [comment]
@saschawo that is exactly the issue! I fixed it in the dev version [here](https://github.com/charlie86/spotifyr/commit/12fd461811cbf9c00382db15a139d1ea9e9a3a3d) and have submitted a CRAN update, but it hasn't been pushed through yet. If you use the dev version you should be good to go.

**Comment by saschawo** [comment]
Great, thank you again for the great package!
