### ISSUE TITLE
Keep getting redirected to illegal scope web page

### ISSUE THREAD

**Issue by justinmiller1104** [charlie86/spotifyr#78]
Hi,
Whenever I try to access data that pertains to my personal details I keep getting redirected to a webpage that displays "Illegal Scope", I was able to successfully replicate your Beatles example on the read me but using this code
get_my_recently_played(limit = 5) %>% 
    mutate(artist.name = map_chr(track.artists, function(x) x$name[1]),
           played_at = as_datetime(played_at)) %>% 
    select(track.name, artist.name, track.album.name, played_at) %>% 
    kable()

Doesn't work for me. Is there any function to change the scope using Spotifyr?

**Comment by charlie86** [comment]
@justinmiller1104 There was recently a change to the spotify api that broke the search function when there's a space in the string. I updated the dev version and am waiting on a CRAN release. If you install the latest dev version you should be good.

`devtools::install_github('charlie86/spotifyr')`

**Comment by tmikolajczyk** [comment]
I think this information should be posted somewhere in README because it's important

**Comment by jcpasion** [comment]
Agreed, I think it should be posted in the README.
