### ISSUE TITLE
Skip interactive shell

### ISSUE THREAD

**Issue by Lef-F** [charlie86/spotifyr#8]
Is there a way to immediately pick the first result from the Spotify artist search results?
Famous bands usually come first and it would be nice to automate the process of getting data for multiple artists without having to type the names in the terminal each time. 🍻

**Comment by charlie86** [comment]
Hey @Lef-F, thanks for the comment. Right after releasing to CRAN I realized it was a bad idea to need the prompt each time, and in the development version what you describe is the default behavior. I'll push the update to CRAN soon.
