### ISSUE TITLE
Is there an easy way to get a random public playlist?

### ISSUE THREAD

**Issue by alexpghayes** [charlie86/spotifyr#81]

**Comment by charlie86** [comment]
@alexpghayes not that i know of - what's your use case?

**Comment by alexpghayes** [comment]
I want to cluster songs based on cooccurence in user playlists.

**Comment by charlie86** [comment]
That sounds really interesting! Though you can't get a random list of playlists, you could use the search function to find public playlists with similar names. 

Say if you were interested in cooccurrence in workout playlists, you could search for playlists with "workout" in the title.

workout_playlists <- `search_spotify('workout', type = 'playlist', include_meta_info = TRUE)`

If you look at `workout_playlists$playlists$total`, you'll see the total number of playlists returned. You can then loop through them using `limit = 50` and `offset` to get as many as you want in groups of 50. Say you wanted 500:

```
all_playlists <- purrr::map_df(1:10, function(x) {
    offset <- (x * 50) - 50
    print(offset)
    search_spotify('workout', type = 'playlist', limit = 50, offset = offset)
})
```

**Comment by charlie86** [comment]
@alexpghayes let me know if that makes sense
