### ISSUE TITLE
search_spotify command does not appear to search in track names

### ISSUE THREAD

**Issue by Midnightokar** [charlie86/spotifyr#83]
I can’t get the SpotifyR package to extract songs which have a specific title using the search_spotify command

Reproducible example below:
library(spotifyr)
Sys.setenv(SPOTIFY_CLIENT_ID = ‘myID’)
Sys.setenv(SPOTIFY_CLIENT_SECRET = ‘myCLIENTSECRET’)
access_token <- get_spotify_access_token()
searchresults <- search_spotify('Zooropa','track')

I would expect the results of this to be the Spotify tracks with the title “Zooropa”. This should be 7 results due to the presence of karaoke and tribute songs which include Zooropa in the track title. Instead the results are 16 observations, including every one of the 10 tracks on the Zooropa album, even those not called Zooropa (e.g. Lemon and Babyface).

Since I am searching in the ‘track’ field I don’t understand why I get the extra 9 results. I'm not sure if this is an error in the package or I am not understanding the command correctly.

**Comment by charlie86** [comment]
@Midnightokar I understand what you're saying, but that's the desired functionality from the Spotify API, and `spotifyr` is just a wrapper around that.
