### ISSUE TITLE
Get the "musical genre" of the tracks of a playlist.

### ISSUE THREAD

**Issue by EmmanuelHeis** [charlie86/spotifyr#85]
First of all thanks for this amazing package its one of the best thing i cam across recently <3 

I was wondering if it was possible to get the musical genre of each track from a playlist owned by a user. In other other adding "musical genres" to the features already present in the function "get_playlist_audio_features". 

If it is possible how ? If its not possible how could we make it possible ? 

If there are already informations about this i apologize, but i did not found any, it seems that its possible get information about the genre only for the artists.

**Comment by charlie86** [comment]
@EmmanuelHeis Genre is defined by artist (not track), so you could use the `get_artists()` function for each artist for each track in the playlist
