### ISSUE TITLE
get_playlist or get_playlist_tracks function for >100 song playlist

### ISSUE THREAD

**Issue by drew-walkerr** [charlie86/spotifyr#86]
Hello ,

I ran into the issue where get_playlist can only get a maximum of 100 tracks from a playlist at a time. Is it possible to repeat this function and offset the object it starts at by 100 each time? To run it until it pulls everything from the playlist? I was trying to do this but my playlist has ~1800 songs or so. Not sure if I just put get_playlist("playlist_id", offset = 100)?

**Comment by charlie86** [comment]
@drew-walkerr

You can use `get_playlist_audio_features()`, which will take care of the looping for you (and add in audio characteristics for each track).

But if you want to do it manually, you can see how many tracks are in the playlist with `include_meta_info = TRUE` (the number of tracks in the playlist is in the `total` list item. Then you can loop through using offset and intervals of 100.
