### ISSUE TITLE
Missing required parameter: client_id

### ISSUE THREAD

**Issue by tmikolajczyk** [charlie86/spotifyr#87]
When collecting users data there is a problem with authentication. `client_id` is missing parameter in web browser and error in R occurs:

`> get_my_recently_played(limit = 5) `
`Waiting for authentication in browser...`
`Press Esc/Ctrl + C to abort`
`Authentication complete.`
`Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  : 
  Bad Request (HTTP 400). Failed to get an access token.`

**Comment by tmikolajczyk** [comment]
Solved. Sorry

**Comment by VaibhavSingh033** [comment]
Hi, can you please share how to rectify this, I get the same error still

**Comment by tmikolajczyk** [comment]
Hi @VaibhavSingh033 

the code that worked for me: 

```
Sys.setenv(SPOTIFY_CLIENT_ID = id)
Sys.setenv(SPOTIFY_CLIENT_SECRET = secret)
access_token <- get_spotify_access_token()

get_my_recently_played(limit = 5)
```

Hope that helps!
