### ISSUE TITLE
get_playlist_audio_features returns error

### ISSUE THREAD

**Issue by jinyanchen** [charlie86/spotifyr#90]
Error in eval_tidy(enquo(var), var_env) : object 'track.id' not found

**Comment by jcpasion** [comment]
I am getting the same error!

**Comment by jinyanchen** [comment]
> I am getting the same error!

I know!! I think Spotify changed parameters but not the package

**Comment by charlie86** [comment]
@jinyanchen @jcpasion thank you for pointing this out! I just pushed a fix to the dev version, so it should work if you install the latest version from github. Let me know if it's still not working

**Comment by jinyanchen** [comment]
> @jinyanchen @jcpasion thank you for pointing this out! I just pushed a fix to the dev version, so it should work if you install the latest version from github. Let me know if it's still not working

IT WORKS!! Thank you so much!
