### ISSUE TITLE
get_playlist error, cannot coerce type 'environment' to vector of type 'character'

### ISSUE THREAD

**Issue by njcorona** [charlie86/spotifyr#96]
Hi, Charlie.

I'm trying to get data on the tracks in a [playlist](https://open.spotify.com/playlist/0a3fsqpDHy0a9Xo1Vc9BRH) for the Cornell Pep Band.

I'm getting the following error when I run the below code.  It is thrown on the last line, get_playlist_tracks().  I think the code is having trouble interpreting the result of the API call.  Would you be able to help out?  Let me know if I can make my code block any more readable or reproducible.  Thanks!

Error:
`
Error in as.vector(x, "character") : 
  cannot coerce type 'environment' to vector of type 'character'
`

Code:
`library(spotifyr)

SPOTIFY_CLIENT_ID <- "..."
SPOTIFY_CLIENT_SECRET <- "..."

access_token <- get_spotify_access_token(client_id = SPOTIFY_CLIENT_ID,
                                         client_secret = SPOTIFY_CLIENT_SECRET)

playlists <- get_user_playlists(user_id = "21kzjy6co6l2mbkruwwd2cpki", limit = 40, authorization = get_spotify_authorization_code(client_id = SPOTIFY_CLIENT_ID, client_secret = SPOTIFY_CLIENT_SECRET, scope = "playlist-read-private"))
pepband_playlist <- tibble::as_tibble(thingy)[which(tibble::as_tibble(thingy)$tracks.total == 112),]$tracks.href

get_playlist_tracks(playlist_id = "0a3fsqpDHy0a9Xo1Vc9BRH", authorization = get_spotify_authorization_code(client_id = SPOTIFY_CLIENT_ID, client_secret = SPOTIFY_CLIENT_SECRET, scope = "playlist-read-private"))`

**Comment by njcorona** [comment]
Hi, Charlie.

Was able to circumvent my error with 

get_playlist(playlist_id = "0a3fsqpDHy0a9Xo1Vc9BRH", authorization = access_token).

Not sure why that changed the result, but happy nonetheless.  Thanks for your time!

**Comment by charlie86** [comment]
Hey Nicolas,

I believe the issue here is the type of authorization you were using. That
function requires an access token, which is generated from
"get_spotify_access_token()", whereas you were passing an
authorization code.
