### ISSUE TITLE
get_track_audio_features() Manual Title is misleading

### ISSUE THREAD

**Issue by gege-hoho** [charlie86/spotifyr#98]
The title of the `get_track_audio_features()` RDocumentation is "Get audio feature information for a single track identified by its unique Spotify ID", but it is possible to request information for up to 100 tracks. A better title would be "Get audio feature information for up to 100 tracks identified by their unique Spotify ID".

The same applies for: 
https://www.rcharlie.com/spotifyr/reference/index.html

**Comment by antaldaniel** [comment]
Version 2.1.2 does solves this.
